#!/bin/bash

################################################################################

# Allow current host user to access files generated by Docker 'root' user.
chown -R ${HOST_UID}:${HOST_GID} /root/compact_env/
